# Generated by Django 3.0.5 on 2021-05-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('resident', models.CharField(blank=True, max_length=100)),
                ('descrition', models.CharField(blank=True, max_length=255)),
                ('medical_condition', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
