# Generated by Django 3.0.5 on 2021-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='descrition',
            new_name='description',
        ),
    ]
