# Generated by Django 3.0.5 on 2021-05-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_archivedimage_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='labled_image',
            field=models.ImageField(blank=True, upload_to='object_detection/LabelImages'),
        ),
    ]
