# Generated by Django 3.0.5 on 2021-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_camera_labled_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='labled_image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
