# Generated by Django 3.0.5 on 2021-05-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20210517_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detection',
            old_name='enable_the_detection',
            new_name='enable',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='enable',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
