# Generated by Django 3.0.5 on 2021-06-07 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_auto_20210517_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='resident',
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('face_picture', models.ImageField(upload_to='user_profile')),
                ('body_picture', models.ImageField(upload_to='user_profile')),
                ('side_picture', models.ImageField(upload_to='user_profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.Camera')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.Detection')),
            ],
        ),
    ]
