# Generated by Django 3.0.5 on 2021-06-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0014_auto_20210607_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivedImage',
            new_name='ArchivedEvent',
        ),
    ]
