# Generated by Django 3.0.5 on 2021-08-02 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0015_auto_20210622_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.Camera')),
                ('reply_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health.ReplyType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
