# Generated by Django 3.0.5 on 2021-08-02 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_notificationrule_replytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationrule',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='phone_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='health.PhoneNumber'),
            preserve_default=False,
        ),
    ]
