# Generated by Django 3.2.6 on 2021-12-04 11:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_auto_20210802_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
