# Generated by Django 3.2.6 on 2021-12-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_auto_20211204_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrule',
            name='reply_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='health.replytype'),
        ),
    ]
